# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UHXRnRHDgc_MT2MFJ2jjeoIl6Rmnq5Kj
"""

print("Bem-vindo a Pesquisa de Satisfação da Empresa MTX sobre o novo sabor de Sorvete de 'Bolo de Cenoura'")

print('\n')


from  time import sleep 

for contagem in range(0,3):
    sleep(1)

mulheres_maiores_20_bom = 0
mulheres_maiores_30_ruim = 0
homens_pessimo = 0
total_homens = 0
total_mulheres = 0

while True:
    sexo = input("Digite M caso for Mulher e H caso for Homem: ")
    if sexo.upper() == "H":
        total_homens += 1
        avaliacao = input("Digite a avaliação do produto como Muito bom, bom, regular, ruim ou péssimo: ")
        if avaliacao.upper() == "PESSIMO":
            homens_pessimo += 1
    elif sexo.upper() == "M":
        total_mulheres += 1
        idade = int(input("Digite sua idade: "))
        avaliacao = input("Digite a avaliação do produto como Muito bom, bom, regular, ruim ou péssimo: ")
        if idade > 20 and avaliacao.upper() == "BOM":
            mulheres_maiores_20_bom += 1
        elif idade > 30 and avaliacao.upper() == "RUIM":
            mulheres_maiores_30_ruim += 1
    else:
        print("Sexo inválido. Digite M para Mulher e H para Homem")
    
    final = input("Deseja continuar a pesquisa? (S/N) ")
    if final.upper() == "N":
        break
print('\n')

print(f"Quantidade de Mulheres maiores de 20 anos que indicaram o produto como 'Bom': {mulheres_maiores_20_bom} \n")
print(f"Quantidade de Mulheres maiores de 30 anos que indicaram o produto como 'Ruim': {mulheres_maiores_30_ruim} \n")
print(f"Quantidade de Homens que indicaram o produto como 'Péssimo': {homens_pessimo}\n")
print(f"Total de Homens que participaram da pesquisa: {total_homens}\n")
print(f"Total de Mulheres que participaram da pesquisa: {total_mulheres}\n")